<?php
$settings = require __DIR__ . "/../src/settings.php";
$URLBASE = (URLBASE != "" ? URLBASE : $_SERVER['REDIRECT_BASE']) . "/";
?><!DOCTYPE html>
<html lang="cs">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>BakaSync</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="icon" type="image/x-icon" href="<?=$URLBASE?>assets/favicon.ico" />
    <link rel="stylesheet" href="<?=$URLBASE?>assets/style.css">

    <link rel="apple-touch-icon" sizes="180x180" href="<?=$URLBASE?>assets/favicons/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="<?=$URLBASE?>assets/favicons/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="<?=$URLBASE?>assets/favicons/favicon-16x16.png">
    <link rel="manifest" href="<?=$URLBASE?>assets/favicons/site.webmanifest">
    <link rel="mask-icon" href="<?=$URLBASE?>assets/favicons/safari-pinned-tab.svg" color="#5bbad5">
    <link rel="shortcut icon" href="<?=$URLBASE?>assets/favicons/favicon.ico">
    <meta name="apple-mobile-web-app-title" content="BakaSync">
    <meta name="application-name" content="BakaSync">
    <meta name="msapplication-TileColor" content="#00aba9">
    <meta name="msapplication-config" content="<?=$URLBASE?>assets/favicons/browserconfig.xml">
    <meta name="theme-color" content="#ffffff">
</head>
<body>

<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
    <a class="ml-md-3 text-dark mr-md-auto mb-2 mb-md-0" style="text-decoration: none;" href="<?=$URLBASE?>" aria-label="BakaSync">
        <img src="<?=$URLBASE?>assets/img/bakasync128.png" class="d-inline-block" style="margin-top: -6px" width="38px" />
        <h5 class="d-inline-block font-weight-normal ml-1" style="margin-top: 6px">BakaSync</h5>
    </a>
    <?php if ($auth->logged()):?>
    <nav class="nav d-block d-md-flex my-2 my-md-0 mr-md-3">
        <li class="nav-item dropdown d-flex">
            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"><?=$auth->getUname()?></a>
            <div class="dropdown-menu">
                <a class="dropdown-item" href="<?=$router->pathFor('config')?>">Nastavení</a>
                <a class="dropdown-item" href="https://brana.textilniskola.cz/">Brána</a>
                <div class="dropdown-divider d-md-none"></div>
                <a class="dropdown-item d-md-none" href="<?=$URLBASE?>logout">Odhlásit</a>
            </div>
        </li>
        <li class="nav-item d-none d-md-block">
            <a class="btn btn-outline-primary mr-md-3" href="<?=$URLBASE?>logout">Odhlásit</a>
        </li>
    </nav>
    <?php else:?>
    <a class="btn btn-outline-primary" href="<?=$URLBASE?>login">Přihlásit</a>
    <?php endif;?>
</div>