<?php include "header.phtml"?>
<div class="container">
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">Dashboard</h1>
    <div class="btn-toolbar mb-2 mb-md-0">
        <div class="btn-group mr-2">
            <button class="btn btn-sm btn-outline-secondary">Aktualizovat</button>
            <button class="btn btn-sm btn-outline-secondary">Export</button>
        </div>
        <button class="btn btn-sm btn-outline-secondary dropdown-toggle">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-calendar"><rect x="3" y="4" width="18" height="18" rx="2" ry="2"></rect><line x1="16" y1="2" x2="16" y2="6"></line><line x1="8" y1="2" x2="8" y2="6"></line><line x1="3" y1="10" x2="21" y2="10"></line></svg>
            This week
        </button>
    </div>
</div>
<div class="row">
<div class="col-12 col-lg-10 col-md-9">
<div class="card border-danger mb-3">
  <div class="card-body text-danger">
    <h5 class="card-title">Upozornění</h5>
    <p class="card-text"><b>2</b> studenté a <b>3</b> učitelé vyžadují aktivitu</p>
  </div>
</div>
<div class="card">
  <div class="card-header">
    <ul class="nav nav-tabs card-header-tabs" role="tablist">
      <li class="nav-item">
        <a class="nav-link active" id="students-tab" data-toggle="tab" href="#students" role="tab" aria-controls="students" aria-selected="true">Studenté <span class="badge badge-dark">2</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="teachers-tab" data-toggle="tab" href="#teachers" role="tab" aria-controls="teachers" aria-selected="false">Učitelé <span class="badge badge-dark">3</span></a>
      </li>
    </ul>
  </div>
  <div class="card-body">
  <div class="tab-content">
    <div class="tab-pane fade show active" id="students" role="tabpanel" aria-labelledby="students-tab">

    <div class="accordion" id="accordionStudents">
      <div class="card">
        <div class="card-header" id="hdStu1">
          <h6 class="mb-0">
            <div class="form-check">
              <input class="form-check-input position-static" type="checkbox" name="option1">
              <label class="form-check-label" style="cursor: pointer;" data-toggle="collapse" data-target="#colStud1" aria-expanded="false" aria-controls="colStud1">Aneta Myšková (4.C)</label>
            </div>
          </h6>
        </div>
        <div id="colStud1" class="collapse" aria-labelledby="heahdStu1dingOne" data-parent="#accordionStudents">
          <div class="card-body">
            <div class="row">
              <div class="col-6">
                <div class="card border-light mb-3">
                  <div class="card-header"><h5 class="my-0">Bakaláři</h5></div>
                  <div class="card-body pb-0">
                    <h6 class="text-danger">Nenalezeno</h6>
                  </div>
                </div>
              </div>
              <div class="col-6">
                <div class="card border-light mb-3">
                  <div class="card-header"><h5 class="my-0">LDAP</h5></div>
                  <div class="card-body pb-0">
                    <dl class="row">
                      <dt class="col-sm-3">Jméno</dt>
                      <dd class="col-sm-9">Aneta</dd>

                      <dt class="col-sm-3">Příjmení</dt>
                      <dd class="col-sm-9">Myšková</dd>

                      <dt class="col-sm-3">Třída</dt>
                      <dd class="col-sm-9">4.C</dd>
                      
                    </dl>
                  </div>
                </div>
              </div>
            </div>
            <div class="alert alert-info" role="alert">
              Doporučená akce: <strong>Přesunout mezi absolventy</strong>
              <button type="button" style="margin-top: -3px;" class="btn btn-success btn-sm float-right">Provést</button>
            </div>
          </div>
        </div>
      </div>


      <div class="card">
        <div class="card-header" id="hdStu2">
          <h6 class="mb-0">
            <div class="form-check">
              <input class="form-check-input position-static" type="checkbox" name="option2">
              <label class="form-check-label" style="cursor: pointer;" data-toggle="collapse" data-target="#colStud2" aria-expanded="false" aria-controls="colStud2">Kateřina Novotná (3.M)</label>
            </div>
          </h6>
        </div>
        <div id="colStud2" class="collapse" aria-labelledby="hdStu2" data-parent="#accordionStudents">
          <div class="card-body">
          <div class="row">
              <div class="col-6">
                <div class="card border-light mb-3">
                  <div class="card-header"><h5 class="my-0">Bakaláři</h5></div>
                  <div class="card-body pb-0">
                    <dl class="row">
                      <dt class="col-sm-3">Jméno</dt>
                      <dd class="col-sm-9">Kateřina</dd>

                      <dt class="col-sm-3">Příjmení</dt>
                      <dd class="col-sm-9">Novotná</dd>

                      <dt class="col-sm-3">Třída</dt>
                      <dd class="col-sm-9">4.M</dd>
                      
                    </dl>
                  </div>
                </div>
              </div>
              <div class="col-6">
                <div class="card border-light mb-3">
                  <div class="card-header"><h5 class="my-0">LDAP</h5></div>
                  <div class="card-body pb-0">
                    <dl class="row">
                      <dt class="col-sm-3">Jméno</dt>
                      <dd class="col-sm-9">Kateřina</dd>

                      <dt class="col-sm-3">Příjmení</dt>
                      <dd class="col-sm-9">Novotná</dd>

                      <dt class="col-sm-3 text-danger">Třída</dt>
                      <dd class="col-sm-9 text-danger">3.M</dd>
                      
                    </dl>
                  </div>
                </div>
              </div>
            </div>
            <div class="alert alert-info" role="alert">
              Doporučená akce: <strong>Změna třídy</strong>
              <button type="button" style="margin-top: -3px;" class="btn btn-success btn-sm float-right">Provést</button>
            </div>
          </div>
        </div>
      </div>
      <div class="card">
        <div class="card-body py-2">
        <button class="btn btn-success">Provést</button> u zvolených studentů doporučené akce
        </div>
      </div>
    </div>
    </div>
    <div class="tab-pane fade" id="teachers" role="tabpanel" aria-labelledby="teachers-tab">
        moo
    </div>
  </div>
  </div>
</div>
</div>
<div class="col-12 col-lg-2 col-md-3 mt-3 mt-md-0">
<div class="card text-white bg-info mb-3">
  <div class="card-header">Stav</div>
  <div class="card-body">
    <h5 class="card-title">Bakaláři</h5>
    <p class="card-text"><b>25</b> studentů<br /><b>15</b> učitelů</p>
    <hr>
    <h5 class="card-title">LDAP</h5>
    <p class="card-text"><b>22</b> studentů<br /><b>14</b> učitelů</p>
  </div>
</div>
</div>
</div>
</div>
<?php include "footer.phtml"?>