<?php include "header.phtml"?>
<div class="container">
<div class="px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
      <h1 class="display-4">Přihlaste se, prosím</h1>
      <p class="lead mt-4">
        Aplikace BakaSync je přístupná pouze administrátorům.<br />
        <span class="font-weight-normal">Pokud nevíte, jak jste se sem dostali, pak zde nemáte co dělat!</span>
      </p>
</div>
</div>
<?php include "footer.phtml"?>