<?php

class generate {
    function __construct($data) {
        $this->conf = $data['conf'];
        $this->tests = $data['tests'];
        $this->schema = $data['schema'];
    }

    function input() {
        return $this->inputTree($this->schema);
    }

    private function inputTree($tree, $path = '') {
        $end = '';
        if ($path != '') {
            $pos = @end(explode("/",$path));
            if (!array_key_exists($pos, $this->tests)) {
                $ret = '<div class="card mt-4">' . PHP_EOL;
            } else if ($this->tests[$pos] == 0) {
                $ret = '<div class="card border-danger mt-4">' . PHP_EOL;
            } else if ($this->tests[$pos] == 1) {
                $ret = '<div class="card border-success mt-4">' . PHP_EOL;
            }
            if (array_key_exists('_desc', $tree)) {
                $ret .= "<h5 class=\"card-header\">{$tree['_desc']}</h5>" . PHP_EOL;
                $end = '</div>';
                unset($tree['_desc']);
            }
            $ret .= '<div class="card-body">' . PHP_EOL;
        } else $ret = '';

        foreach ($tree as $key => $field) {
            $fp = $path . "/" . $key;
            if (is_array($field)) {
                if (count($field) == 1 && array_key_exists(0, $field)) {
                    $ret .= <<<EOL
<div class="form-group row">
<label class="col-md-3 col-form-label" for="$fp">{$field[0]}</label>
<div class="col-md-9">
<textarea style="resize: none; overflow: scroll;" class="form-control" id="$fp" name="$fp" rows="5">{$this->conf[$fp]}</textarea>
</div>
</div>
EOL;
                } else {
                    $ret .= $this->inputTree($field, $fp);
                }
            } else {
                $ret .= '<div class="form-group row">' . PHP_EOL;
                $ret .= "<label class=\"col-md-3 col-form-label\" for=\"$fp\">$field</label>" . PHP_EOL;
                if ($key == '_pass') {
                    $pass = str_repeat("*", strlen($this->conf[$fp]) ? 15 : 0);
                    $ret .= "<div class=\"col-md-9\"><strong><input class=\"form-control\" type=\"password\" name=\"$fp\" id=\"$fp\" value=\"$pass\"></strong></div>" . PHP_EOL;
                } else {
                    $ret .= "<div class=\"col-md-9\"><strong><input class=\"form-control\" type=\"text\" name=\"$fp\" id=\"$fp\" value=\"{$this->conf[$fp]}\"></strong></div>" . PHP_EOL;
                }
                $ret .= '</div>' . PHP_EOL;
            }
        }
        $ret .= $path == '' ? '' : '</div>' . $end;
        return $ret;
    }
}

$generate = new generate($data);

include "header.phtml"?>
<div class="container">
<form method="post" action="<?=$router->pathFor('setup')?>">
<input type="hidden" name="_METHOD" value="PUT" />
<input type="hidden" name="<?= $csrf['nameKey'] ?>" value="<?= $csrf['name'] ?>">
<input type="hidden" name="<?= $csrf['valueKey'] ?>" value="<?= $csrf['value'] ?>">
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">První spuštění
<?php
if (is_array(@$error)):
    foreach ($error as $message):
?>
    <small class="text-danger ml-3"><?=$message['message']?></small>
<?php
    endforeach;
elseif(is_array(@$success)):
    foreach ($success as $message):
?>
    <small class="text-muted ml-3"><?=$message['message']?></small>
<?php
    endforeach;
endif;
?>
    </h1>
    <div class="btn-toolbar mb-2 mb-md-0">
        <div class="btn-group mr-2">
            <?php if (is_array(@$success)):?>
            <button class="btn btn-sm btn-outline-secondary" onclick="window.location.reload()">Pokračovat</button>
            <?php else:?>
            <button class="btn btn-sm btn-outline-secondary" onclick="window.location.reload()">Obnovit</button>
            <button class="btn btn-sm btn-outline-secondary">Test</button>
            <?php endif;?>
        </div>
    </div>
</div>
<?=$generate->input()?>
</form>
</div>
<?php include "footer.phtml"?>